CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB;

INSERT INTO roles (nombre) VALUES ('admin'), ('empleado'), ('cliente');

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMP DEFAULT NULL,
    hash VARCHAR(128) NOT NULL,
    salt VARCHAR(64) NOT NULL,
    FOREIGN KEY (rol) REFERENCES roles(nombre)
) ENGINE=InnoDB;

ALTER TABLE users
ADD not_archived BOOLEAN
GENERATED ALWAYS AS (IF(deleted_at IS NULL, 1, NULL)) VIRTUAL;

ALTER TABLE users
ADD CONSTRAINT UNIQUE (email, not_archived);