### POST Login with email and password
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "admin1@email.com",
    "password": "1234"
}

### GET Get protected resource
GET http://localhost:3000/auth/validate-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImlhdCI6MTcyNDE3ODc1ODUwOCwibm9tYnJlIjoiQ2xpZW50ZSAxIiwiZW1haWwiOiJjbGllbnRlMUBlbWFpbC5jb20iLCJyb2wiOiJjbGllbnRlIiwiZXhwIjoxNzI0MTc4ODQ0OTA4fQ.BfgNW8HyCq5yeu1UZ9_haljwdEmRuyXWMdTn25MGyefPDyYxigvaW3aPpi0sdNoTomUja-1tDtJUy9KG007zXcO7cimrCHKveZ0uFiGdvyjROeVVlqQBJ0ZXJU2ePFtN2ayVd5Sc1TG03kW5x1hka6sIgitGlErB7fp-NuArO0VBeal9HvxZ7uaDv4qgzamsy71Etx5RGGCm-f-qvzYjJK_-aK9ww_M9qd4k_cmFwDBEQex4z6YIlpXpfm_8JY2fnvO5_9qWeGvD0yZExPNUxVXpcQGYHbmkSBbl_JLcNqFFT7zpuiyWbOmAnbbUqmccmw66uYsKGCzibWrcnklhQ45QfZPBsGsZGFKnS7UKOmtBOOoqvUAn_oTY_cmrdw1o1d3EPGMI-G5BQMmraptt8vWEhTGx2KEt2ott_mbCz8tNWU8831IV9_wbgh6qmWTZNwhVlmE7FEkbIvrDwbPMLTgoY0VQQO4CeH5x_oo5pH_DmL509BUcKzOI4-A2CZxJjNJ9YuH_jCxdU7he-uUC-uBGd9ylZK0Lpys0zFVo0qCERLji38MbRKWMt3KkgMNE6baLzsrDrk1Yhx4JbpxhigXMGYLAS3GDwzLdD2D55zjYfkfoGNkT2HWV03i1ecNmClQtSVmr3yjaHWANZvAhJ8Adq68zfjPQeo_fiLKfZxQ

### GET Read Owner resource
GET http://localhost:3000/auth/validate-owner?owner=8
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImlhdCI6MTcyNDE3ODc1ODUwOCwibm9tYnJlIjoiQ2xpZW50ZSAxIiwiZW1haWwiOiJjbGllbnRlMUBlbWFpbC5jb20iLCJyb2wiOiJjbGllbnRlIiwiZXhwIjoxNzI0MTc4ODQ0OTA4fQ.BfgNW8HyCq5yeu1UZ9_haljwdEmRuyXWMdTn25MGyefPDyYxigvaW3aPpi0sdNoTomUja-1tDtJUy9KG007zXcO7cimrCHKveZ0uFiGdvyjROeVVlqQBJ0ZXJU2ePFtN2ayVd5Sc1TG03kW5x1hka6sIgitGlErB7fp-NuArO0VBeal9HvxZ7uaDv4qgzamsy71Etx5RGGCm-f-qvzYjJK_-aK9ww_M9qd4k_cmFwDBEQex4z6YIlpXpfm_8JY2fnvO5_9qWeGvD0yZExPNUxVXpcQGYHbmkSBbl_JLcNqFFT7zpuiyWbOmAnbbUqmccmw66uYsKGCzibWrcnklhQ45QfZPBsGsZGFKnS7UKOmtBOOoqvUAn_oTY_cmrdw1o1d3EPGMI-G5BQMmraptt8vWEhTGx2KEt2ott_mbCz8tNWU8831IV9_wbgh6qmWTZNwhVlmE7FEkbIvrDwbPMLTgoY0VQQO4CeH5x_oo5pH_DmL509BUcKzOI4-A2CZxJjNJ9YuH_jCxdU7he-uUC-uBGd9ylZK0Lpys0zFVo0qCERLji38MbRKWMt3KkgMNE6baLzsrDrk1Yhx4JbpxhigXMGYLAS3GDwzLdD2D55zjYfkfoGNkT2HWV03i1ecNmClQtSVmr3yjaHWANZvAhJ8Adq68zfjPQeo_fiLKfZxQ

### GET Read Admin resource
GET http://localhost:3000/auth/validate-admin
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTcyNDE3ODg3MDAwNiwibm9tYnJlIjoiQWRtaW4gMSIsImVtYWlsIjoiYWRtaW4xQGVtYWlsLmNvbSIsInJvbCI6ImFkbWluIiwiZXhwIjoxNzI0MTc4OTU2NDA2fQ.InK_xYC6CduxAvMoNWo_P6OTBX5Wk6hbhkk5I9H5-0aaTuMBtzRC-CmfPFfZZaGrcse3ZFhPkRa2dLpC1vLSB9zwq2Udr-bXJM8KpLzoMQZbyZ6iA_ZDmSIexXRnaxDNR0sxc-qd6V8sqwYHjJ3XWfG7qJQWDeZ1JBIChnmGQQwmQAElHggmn_1m4w1xhL6YRTNMUjpo-AsVE1LJhdIsGlf8WDq0DcfJIlKn6VdGUbaUa5AaWOzdn5AEBphbp6HVv1MFcl0XIdWqy6YdQEBv5msBAgzaTjYpHWAytezhtsIfXpp7_JXb3EY7W9f6u6M9aUHlUZTv0CoWs0iL4ZyZHub3mkBC0zWM_Qn8WWPHAlIvgfWKldXAg-ryaiIAF1govpLUYlBAe0OoHhQpOykghgV2Mgf0e25ZSQuDFnF7u7GYGWQi4Tti_5Zm3cUS9PSo_d02sJ4-MLOCTPVgICDXtUJEEJa94C0Q9PajKHGvwc66fkZrMv0r2bHXeBDdTqG2HdfeSIXfnn0shNy-W7W8ei2izMRTc7-FKhmHgqJCvK_YXrxSFzJPZ_BWcNvNhZcIY7SJasGeVGkjP3-lIqhY36aGQR8q8rusqevUksiecK-IwNs59klGC6GI2L111DCWEvaAJHYIlAv1u23kF6h5vrsILnWpwRqokQIGYkGaV0s