### GET Read All Users
GET http://localhost:3000/users HTTP/1.1

### POST Create new User
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "nombre": "Cliente 1",
  "password": "1234",
  "email": "cliente1@email.com",
  "rol": "cliente"
}

### GET Read User by ID
GET http://localhost:3000/users/1 HTTP/1.1


### PUT Update User by ID
PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "nombre": "Admin 1 New",
  "contrasena": "new_contrasena",
  "email": "admin1@email.com",
  "rol": "admin"
}

### DELETE Delete User by ID
DELETE http://localhost:3000/users/1 HTTP/1.1
Authorization: Bearer YOUR_ACCESS_TOKEN

### GET Read User by Email
GET http://localhost:3000/users?email=admin1@email.com HTTP/1.1

### GET Read Deleted Users
GET http://localhost:3000/users?deleted=true HTTP/1.1