### GET Read All Users
GET http://localhost:3000/users HTTP/1.1

### POST Create new User
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "nombre": "Usuario 1",
  "contrasena": "contrasena",
  "email": "user1@email.com",
  "rol": "cliente"
}

### GET Read User by ID
GET http://localhost:3000/users/1 HTTP/1.1


### PUT Update User by ID
PUT http://localhost:3000/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
  "nombre": "Usuario 1 New",
  "contrasena": "new_contrasena",
  "email": "user1.new@email.com",
  "rol": "cliente"
}